name: Auto package, tag, release on PR

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'  # 忽略文档更新，避免不必要的运行
  workflow_dispatch:  # 允许手动触发

jobs:
  build-and-release:
    runs-on: windows-latest  # 使用Windows环境[1](@ref)
    env:
      PYTHONIOENCODING: "utf-8"
      PYTHONUTF8: "1"  # 强制使用UTF-8编码[1,3](@ref)
    permissions:
      contents: write  # 允许创建Tag和Release[2](@ref)

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        ref: main  # 明确检出main分支[5](@ref)

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10.x'  # 使用最新的稳定3.10.x版本[3](@ref)
        cache: 'pip'

    - name: Upgrade pip and install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Extract version number
      id: get_version
      run: |
        $version = python package.py -v
        echo "VERSION_NUMBER=$version" >> $env:GITHUB_OUTPUT

    # 新增的标签检查步骤
    - name: Check for existing tag
      id: check_tag
      run: |
        $tag = "BAAH${{ steps.get_version.outputs.VERSION_NUMBER }}"
        $result = git ls-remote --tags origin $tag
        if ($result) {
            Write-Output "::error::Already has this tag: $tag"
            exit 1
        } else {
            Write-Output "Tag $tag does not exist. Proceeding."
        }

    - name: Extract version change log
      id: get_change_log
      run: |
        $version_log = python package.py -c
        echo "VERSION_LOG=$version_log" >> $env:GITHUB_OUTPUT

    - name: Build package
      run: python package.py  # 执行打包脚本[8](@ref)

    - name: Create Git Tag
      run: |
        git tag "BAAH${{ steps.get_version.outputs.VERSION_NUMBER }}"
        git push origin "BAAH${{ steps.get_version.outputs.VERSION_NUMBER }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用内置令牌[2](@ref)

    - name: Create Release
      uses: softprops/action-gh-release@v2  # 功能完整的Release Action[2,10](@ref)
      with:
        draft: false
        prerelease: false
        tag_name: BAAH${{ steps.get_version.outputs.VERSION_NUMBER }}
        name: BAAH${{ steps.get_version.outputs.VERSION_NUMBER }}
        body: |
          ${{ steps.get_change_log.outputs.VERSION_LOG }}
        files: ./dist/*.zip  # 仅上传ZIP格式的制品[10](@ref)
